import type { DevelopmentCampaignLayer } from "./developmentCampaignTypes";

export const defaultDevelopmentCampaignLayers: DevelopmentCampaignLayer[] = [
  {
    layerId: "SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1",
    layerName: "Session context and conversation memory Phase 1",
    status: "real",
    priority: 92,
    dependencyLayerIds: [],
    riskLevel: "LOW",
    truthfulnessRequirements: ["Label local-browser storage honestly", "Do not claim cross-browser or long-term AI memory"],
    completionCriteria: ["Follow-ups resolve against active chat context", "Missing context produces truthful clarification"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevChat.test.ts", "./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevDurableSessionStore.test.ts", "npm run build"],
    nextActions: ["Use this as a dependency for durable project/task state planning"],
  },
  {
    layerId: "DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1",
    layerName: "Durable project memory and task state Phase 1",
    status: "real",
    priority: 100,
    dependencyLayerIds: ["SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1", "AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Distinguish local-browser storage from long-term AI memory", "Persist only explicit project/task state", "Never claim cross-browser or server durable memory"],
    completionCriteria: ["Typed storage adapter exists", "Project/task state survives browser page reload in the same browser", "Read/write tests cover missing and corrupt state"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevDurableSessionStore.test.ts", "./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevChat.test.ts", "npm run build"],
    nextActions: ["Use local-browser state as the baseline for project inspection planning", "Add server-backed storage only in a later explicit persistence phase"],
  },
  {
    layerId: "PROJECT_STATE_INSPECTION_PHASE1",
    layerName: "Project state inspection Phase 1",
    status: "missing",
    priority: 86,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Report only inspected files/state", "Separate inferred project state from verified project state"],
    completionCriteria: ["Bounded project scanner exists", "Inspection output feeds planning without executing changes"],
    verificationCommands: ["npm run build"],
    nextActions: ["Create read-only inspection contract", "Add verified/unverified flags"],
  },
  {
    layerId: "AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1",
    layerName: "Autonomous development campaign engine Phase 1",
    status: "real",
    priority: 98,
    dependencyLayerIds: ["SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1"],
    riskLevel: "LOW",
    truthfulnessRequirements: ["Planning only", "No autonomous repo editing", "No fake execution claims", "Label blocked and scaffolded layers"],
    completionCriteria: ["Capability map is typed", "Highest-impact unblocked layer is selected", "Safe handoff is generated", "Chat can answer what to build next"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/developmentCampaign.test.ts", "npm run build"],
    nextActions: ["Expose campaign result in chat", "Document current and next layer"],
  },
  {
    layerId: "SUPERVISED_MULTI_STEP_EXECUTION_PHASE1",
    layerName: "Supervised multi-step execution Phase 1",
    status: "missing",
    priority: 93,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Require explicit operator approval", "No hands-off execution", "Record planned vs executed actions separately"],
    completionCriteria: ["Multi-step plans remain approval-gated", "Execution remains supervised and auditable"],
    verificationCommands: ["npm run build"],
    nextActions: ["Create supervised plan queue", "Add approval metadata"],
  },
  {
    layerId: "OUTCOME_LEARNING_AND_RETROSPECTIVE_MEMORY_PHASE1",
    layerName: "Outcome learning and retrospective memory Phase 1",
    status: "missing",
    priority: 82,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Learning is advisory until applied by explicit review", "Do not mutate behavior from unreviewed outcomes"],
    completionCriteria: ["Outcomes are recorded", "Retrospective summaries are explicit and non-executing"],
    verificationCommands: ["npm run build"],
    nextActions: ["Define outcome record schema", "Add retrospective summary generator"],
  },
  {
    layerId: "UNITY_WORKFLOW_AWARENESS_PHASE1",
    layerName: "Unity workflow awareness Phase 1",
    status: "missing",
    priority: 78,
    dependencyLayerIds: ["PROJECT_STATE_INSPECTION_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Do not claim Unity Editor control", "Separate Unity advice from verified Unity state"],
    completionCriteria: ["Unity-specific project facts are represented", "Unity validation remains explicitly unavailable unless real bridge runs"],
    verificationCommands: ["npm run build"],
    nextActions: ["Model scenes, prefabs, scripts, and validation availability"],
  },
  {
    layerId: "CODEBASE_CHANGE_PLANNING_PHASE1",
    layerName: "Codebase change planning Phase 1",
    status: "missing",
    priority: 84,
    dependencyLayerIds: ["PROJECT_STATE_INSPECTION_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Plans are not edits", "Only report changed files after actual implementation"],
    completionCriteria: ["Change plans name files, risks, tests, and rollback notes", "No automatic mutation occurs"],
    verificationCommands: ["npm run build"],
    nextActions: ["Create bounded change-plan schema", "Connect to project inspection output"],
  },
  {
    layerId: "SAFE_EXECUTION_GUARDRAILS_PHASE1",
    layerName: "Safe execution guardrails Phase 1",
    status: "partial",
    priority: 95,
    dependencyLayerIds: ["AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Guardrails must exist before execution autonomy expands", "Never imply approval-free mutation"],
    completionCriteria: ["Approval gate model exists", "Blocked operations are explicitly reported", "Guardrails are test-covered"],
    verificationCommands: ["npm run build"],
    nextActions: ["Inventory current guardrails", "Define approval and rollback boundaries"],
  },
  {
    layerId: "FULL_HANDS_OFF_STUDIO_OPERATION",
    layerName: "Full hands-off studio operation",
    status: "future",
    priority: 10,
    dependencyLayerIds: ["SUPERVISED_MULTI_STEP_EXECUTION_PHASE1", "OUTCOME_LEARNING_AND_RETROSPECTIVE_MEMORY_PHASE1", "UNITY_WORKFLOW_AWARENESS_PHASE1", "CODEBASE_CHANGE_PLANNING_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "FUTURE_ONLY",
    truthfulnessRequirements: ["Not real", "Do not market as available", "Keep as future target only"],
    completionCriteria: ["All supervised layers are real and verified before any hands-off claim"],
    verificationCommands: ["Not applicable until prerequisites are real"],
    nextActions: ["Do not implement in Phase 1"],
  },
];

export function getDefaultDevelopmentCampaignLayers(): DevelopmentCampaignLayer[] {
  return defaultDevelopmentCampaignLayers.map((layer) => ({
    ...layer,
    dependencyLayerIds: [...layer.dependencyLayerIds],
    truthfulnessRequirements: [...layer.truthfulnessRequirements],
    completionCriteria: [...layer.completionCriteria],
    verificationCommands: [...layer.verificationCommands],
    nextActions: [...layer.nextActions],
  }));
}