import type { DevelopmentCampaignLayer } from "./developmentCampaignTypes";

export const defaultDevelopmentCampaignLayers: DevelopmentCampaignLayer[] = [
  {
    layerId: "SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1",
    layerName: "Session context and conversation memory Phase 1",
    status: "real",
    priority: 92,
    dependencyLayerIds: [],
    riskLevel: "LOW",
    truthfulnessRequirements: ["Label local-browser storage honestly", "Do not claim cross-browser or long-term AI memory"],
    completionCriteria: ["Follow-ups resolve against active chat context", "Missing context produces truthful clarification"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevChat.test.ts", "./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevDurableSessionStore.test.ts", "npm run build"],
    nextActions: ["Use this as a dependency for durable project/task state planning"],
  },
  {
    layerId: "DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1",
    layerName: "Durable project memory and task state Phase 1",
    status: "real",
    priority: 100,
    dependencyLayerIds: ["SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1", "AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Distinguish local-browser storage from long-term AI memory", "Persist only explicit project/task state", "Never claim cross-browser or server durable memory"],
    completionCriteria: ["Typed storage adapter exists", "Project/task state survives browser page reload in the same browser", "Read/write tests cover missing and corrupt state"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevDurableSessionStore.test.ts", "./node_modules/.bin/tsx.cmd --test lib/aie/gameDevChat/gameDevChat.test.ts", "npm run build"],
    nextActions: ["Use local-browser state as the baseline for project inspection planning", "Add server-backed storage only in a later explicit persistence phase"],
  },
  {
    layerId: "PROJECT_STATE_INSPECTION_PHASE1",
    layerName: "Project state inspection Phase 1",
    status: "real",
    priority: 86,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Report only supplied or inspected files/state", "Separate inferred project state from verified project state", "Never claim inspection edited files, ran Unity, or executed tests"],
    completionCriteria: ["Bounded project scanner contract exists", "Inspection output feeds planning without executing changes", "Verified and unverified facts are separated", "Inspection is test-covered"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/projectStateInspection.test.ts", "npm run build"],
    nextActions: ["Use read-only inspection facts as input to codebase change planning", "Keep actual repo scanning and mutation in separate approved paths"],
  },
  {
    layerId: "AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1",
    layerName: "Autonomous development campaign engine Phase 1",
    status: "real",
    priority: 98,
    dependencyLayerIds: ["SESSION_CONTEXT_AND_CONVERSATION_MEMORY_PHASE1"],
    riskLevel: "LOW",
    truthfulnessRequirements: ["Planning only", "No autonomous repo editing", "No fake execution claims", "Label blocked and scaffolded layers"],
    completionCriteria: ["Capability map is typed", "Highest-impact unblocked layer is selected", "Safe handoff is generated", "Chat can answer what to build next"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/developmentCampaign.test.ts", "npm run build"],
    nextActions: ["Expose campaign result in chat", "Document current and next layer"],
  },
  {
    layerId: "SUPERVISED_MULTI_STEP_EXECUTION_PHASE1",
    layerName: "Supervised multi-step execution Phase 1",
    status: "real",
    priority: 93,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Require explicit operator approval", "No hands-off execution", "Record planned vs executed actions separately", "Never claim queued steps have executed"],
    completionCriteria: ["Multi-step plans remain approval-gated", "Execution remains supervised and auditable", "Eligibility checks consume safe guardrail decisions", "Rollback-plan requirements are explicit before mutation eligibility", "Unsupported execution requests are refused"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/supervisedExecutionQueue.test.ts", "npm run build"],
    nextActions: ["Use the supervised queue as the planning-only bridge toward project inspection", "Keep actual execution in a separate approved implementation path"],
  },
  {
    layerId: "OUTCOME_LEARNING_AND_RETROSPECTIVE_MEMORY_PHASE1",
    layerName: "Outcome learning and retrospective memory Phase 1",
    status: "real",
    priority: 82,
    dependencyLayerIds: ["DURABLE_PROJECT_MEMORY_AND_TASK_STATE_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Learning is advisory until applied by explicit review", "Do not mutate behavior from unreviewed outcomes", "Never claim outcome summaries executed or changed code"],
    completionCriteria: ["Outcomes are recorded", "Retrospective summaries are explicit and non-executing", "Reviewed and unreviewed outcomes remain separated", "Behavior mutation stays disabled"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/outcomeRetrospectiveMemory.test.ts", "npm run build"],
    nextActions: ["Use reviewed lessons as advisory context for Unity workflow awareness", "Keep behavior changes behind explicit review and implementation"],
  },
  {
    layerId: "LONG_RUNNING_CAMPAIGN_RUNTIME_PHASE1",
    layerName: "Long-running campaign runtime Phase 1",
    status: "real",
    priority: 90,
    dependencyLayerIds: ["AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1", "SUPERVISED_MULTI_STEP_EXECUTION_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Runtime continuation is modeled and checkpointed only", "Do not claim unattended execution or autonomous shell control", "Label checkpoint persistence scope explicitly"],
    completionCriteria: ["Runtime state tracks elapsed time, active layer, queues, blockers, iteration, failure, recovery, and next action", "Checkpoint contracts support resume metadata and persistence labels", "Continuation logic prefers existing campaigns over restart", "Extended metrics track tests, builds, rollbacks, failures, interruptions, and velocity", "Timestamp summaries include date, hour, minute, second, timezone label, and elapsed runtime"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/longRunningCampaignRuntime.test.ts", "npm run build"],
    nextActions: ["Use long-running runtime state while advancing Unity workflow awareness", "Keep real execution behind explicit supervised paths"],
  },
  {
    layerId: "SCOPED_SUPERVISED_EXECUTION_RUNTIME_PHASE1",
    layerName: "Scoped supervised execution runtime Phase 1",
    status: "real",
    priority: 91,
    dependencyLayerIds: ["SAFE_EXECUTION_GUARDRAILS_PHASE1", "SUPERVISED_MULTI_STEP_EXECUTION_PHASE1", "LONG_RUNNING_CAMPAIGN_RUNTIME_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Only approved allowlisted commands may run", "Do not claim chat ran commands when it only prepared a request", "Log blocked and executed attempts separately", "Keep destructive, credential, install, force-push, and Unity commands blocked"],
    completionCriteria: ["Execution request model exists", "Approval and scope gate exists", "Safe command allowlist exists", "Disabled-by-default Node adapter can really execute approved scoped commands", "Execution logs capture stdout, stderr, exit code, elapsed time, and truthfulness labels", "Campaign state can record execution results"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/scopedSupervisedExecutionRuntime.test.ts", "npm run build"],
    nextActions: ["Use scoped execution for approved low-risk local commands", "Keep Unity execution deferred until Unity workflow awareness is implemented"],
  },
  {
    layerId: "APPROVED_EXECUTION_PIPELINE_PHASE1",
    layerName: "Approved execution pipeline Phase 1",
    status: "real",
    priority: 92,
    dependencyLayerIds: ["SCOPED_SUPERVISED_EXECUTION_RUNTIME_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Browser clients may request approval but never spawn commands", "Trusted server runtime must re-check approval, scope, allowlist, timeout, and rollback before dispatch", "Disabled runtime, simulated approval, blocked execution, and real execution must be labeled separately", "Captured stdout, stderr, exit code, elapsed time, and lifecycle states must be shown without inventing success"],
    completionCriteria: ["Approved execution pipeline controller exists", "Node API route invokes the controller", "Operator chat can approve, reject, and retry prepared requests", "Trusted adapter dispatch remains explicitly enabled only", "Tests cover approval, rejection, blocking, timeout, failure, lifecycle, boundary protection, and real execution"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/approvedExecutionPipeline.test.ts lib/aie/scopedSupervisedExecutionRuntime.test.ts lib/aie/gameDevChat/gameDevChat.test.ts", "npm run build"],
    nextActions: ["Use approved pipeline only for allowlisted local commands", "Keep unattended autonomy and Unity execution blocked"],
    milestoneCategories: ["execution", "validation"],
  },
  {
    layerId: "SCOPED_REPO_MUTATION_AND_PATCH_RUNTIME_PHASE1",
    layerName: "Scoped repo mutation and patch runtime Phase 1",
    status: "real",
    priority: 93,
    dependencyLayerIds: ["APPROVED_EXECUTION_PIPELINE_PHASE1", "SCOPED_SUPERVISED_EXECUTION_RUNTIME_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Only explicitly approved files inside approved directories may be mutated", "Generate diff previews before mutation", "Pre-mutation snapshots must support rollback", "Validation failures must be preserved rather than described as success", "Report milestone count, wall-clock duration, continuation, and retry truthfully"],
    completionCriteria: ["Patch request model exists", "Scoped file mutation boundary blocks unsafe paths, lockfiles, credentials, and unapproved files", "Patch runtime creates diff previews and applies approved writes", "Rollback restores pre-mutation snapshots", "Validation results and supervised retry metadata are captured", "Campaign metadata distinguishes planning, execution, mutation, validation, rollback, and retry milestones"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/scopedRepoMutationRuntime.test.ts lib/aie/approvedExecutionPipeline.test.ts lib/aie/developmentCampaign/developmentCampaign.test.ts lib/aie/gameDevChat/gameDevChat.test.ts", "npm run build"],
    nextActions: ["Use scoped patch runtime only for approved file-specific repo mutations", "Keep unrestricted repo rewrites, secret mutation, destructive deletion, and unattended patching blocked"],
    milestoneCategories: ["planning", "execution", "mutation", "validation", "rollback", "retry"],
  },
  {
    layerId: "UNITY_WORKFLOW_AWARENESS_PHASE1",
    layerName: "Unity workflow awareness Phase 1",
    status: "missing",
    priority: 78,
    dependencyLayerIds: ["PROJECT_STATE_INSPECTION_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Do not claim Unity Editor control", "Separate Unity advice from verified Unity state"],
    completionCriteria: ["Unity-specific project facts are represented", "Unity validation remains explicitly unavailable unless real bridge runs"],
    verificationCommands: ["npm run build"],
    nextActions: ["Model scenes, prefabs, scripts, and validation availability"],
  },
  {
    layerId: "CODEBASE_CHANGE_PLANNING_PHASE1",
    layerName: "Codebase change planning Phase 1",
    status: "real",
    priority: 84,
    dependencyLayerIds: ["PROJECT_STATE_INSPECTION_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "MEDIUM",
    truthfulnessRequirements: ["Plans are not edits", "Only report changed files after actual implementation", "Block unverified target files until inspection verifies them"],
    completionCriteria: ["Change plans name files, risks, tests, and rollback notes", "No automatic mutation occurs", "Plans consume project inspection facts", "Repo mutation approval remains separate from planning"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/codebaseChangePlanning.test.ts", "npm run build"],
    nextActions: ["Use planned change metadata as input for future outcome learning", "Keep patch application in a separate supervised execution path"],
  },
  {
    layerId: "SAFE_EXECUTION_GUARDRAILS_PHASE1",
    layerName: "Safe execution guardrails Phase 1",
    status: "real",
    priority: 95,
    dependencyLayerIds: ["AUTONOMOUS_DEVELOPMENT_CAMPAIGN_ENGINE_PHASE1"],
    riskLevel: "HIGH",
    truthfulnessRequirements: ["Guardrails classify approval and rollback readiness only", "Never imply approval-free mutation", "Never claim the guardrail executed repo, Unity, shell, or agent work"],
    completionCriteria: ["Approval gate model exists", "Blocked operations are explicitly reported", "Guardrails are test-covered", "Rollback boundaries are required before supervised mutation eligibility"],
    verificationCommands: ["./node_modules/.bin/tsx.cmd --test lib/aie/developmentCampaign/safeExecutionGuardrails.test.ts", "npm run build"],
    nextActions: ["Use the guardrail contract as a dependency for supervised multi-step execution planning", "Keep execution paths separate from guardrail classification"],
  },
  {
    layerId: "FULL_HANDS_OFF_STUDIO_OPERATION",
    layerName: "Full hands-off studio operation",
    status: "future",
    priority: 10,
    dependencyLayerIds: ["SUPERVISED_MULTI_STEP_EXECUTION_PHASE1", "OUTCOME_LEARNING_AND_RETROSPECTIVE_MEMORY_PHASE1", "UNITY_WORKFLOW_AWARENESS_PHASE1", "CODEBASE_CHANGE_PLANNING_PHASE1", "SAFE_EXECUTION_GUARDRAILS_PHASE1"],
    riskLevel: "FUTURE_ONLY",
    truthfulnessRequirements: ["Not real", "Do not market as available", "Keep as future target only"],
    completionCriteria: ["All supervised layers are real and verified before any hands-off claim"],
    verificationCommands: ["Not applicable until prerequisites are real"],
    nextActions: ["Do not implement in Phase 1"],
  },
];

export function getDefaultDevelopmentCampaignLayers(): DevelopmentCampaignLayer[] {
  return defaultDevelopmentCampaignLayers.map((layer) => ({
    ...layer,
    dependencyLayerIds: [...layer.dependencyLayerIds],
    truthfulnessRequirements: [...layer.truthfulnessRequirements],
    completionCriteria: [...layer.completionCriteria],
    verificationCommands: [...layer.verificationCommands],
    nextActions: [...layer.nextActions],
  }));
}