"""Manifest-backed capability registry and validation helpers."""
from __future__ import annotations

from .capability_models import CapabilityManifest


class CapabilityManifestError(ValueError):
    """Raised when capability manifest definitions are invalid."""


CAPABILITY_MANIFESTS: tuple[CapabilityManifest, ...] = (
    CapabilityManifest(
        capability_id="telegram.non_text",
        name="Telegram Non-Text",
        category="operator",
        short_description="Reject unsupported non-text Telegram messages.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        user_visible=False,
        include_in_capabilities_summary=False,
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="telegram.parse_failure",
        name="Telegram Parse Failure",
        category="operator",
        short_description="Return a safe correction for malformed Telegram commands.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        user_visible=False,
        include_in_capabilities_summary=False,
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="telegram.plain_text",
        name="Telegram Plain Text",
        category="operator",
        short_description="Classify natural-language Telegram messages and route them through existing safe handlers without bypassing approvals.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        user_visible=False,
        include_in_capabilities_summary=False,
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="telegram.unknown",
        name="Telegram Unknown Command",
        category="operator",
        short_description="Reject unsupported Telegram commands with a short correction.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        user_visible=False,
        include_in_capabilities_summary=False,
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="context.read",
        name="Contexts",
        category="operator",
        short_description="List recent explicit context buffers available to the current Telegram chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="context.clear",
        name="Clear Context",
        category="operator",
        short_description="Clear the explicit context buffers for the current Telegram chat.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        scope_type="internal",
        access_mode="write",
        include_in_capabilities_summary=True,
    ),
    CapabilityManifest(
        capability_id="help.read",
        name="Help",
        category="operator",
        short_description="Show the supported Telegram operator commands.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="nodes.read",
        name="Nodes",
        category="operator",
        short_description="List registered execution nodes and the currently selected target.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="node.view.read",
        name="Node View",
        category="operator",
        short_description="Inspect one registered execution node by id.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="node.select.query",
        name="Node Select",
        category="operator",
        short_description="Select the execution node used for future confirmed bounded run and test actions.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="runtime.activate.query",
        name="Start Runtime",
        category="runtime",
        short_description="Explicitly enable local execution capability without launching external code.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        include_in_capabilities_summary=False,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="node.clear.query",
        name="Node Clear",
        category="operator",
        short_description="Clear the explicit execution node selection and return to the default local node.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="status.read",
        name="Status",
        category="runtime",
        short_description="Read runtime, health, security, readiness, and loop status.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="action.last.read",
        name="Last Action",
        category="operator",
        short_description="Read the latest operator loop action and next explicit step guidance.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="chat.orchestrate.read",
        name="Chat Orchestrator",
        category="operator",
        short_description="Route a natural-language /chat request through deterministic intent classification and existing safe handlers without hiding approvals.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="intent.translate.read",
        name="Intent Translate",
        category="intent",
        short_description="Translate a natural-language product request into a structured intent spec and operator handoff.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="intent.refine.read",
        name="Intent Refine",
        category="intent",
        short_description="Refine the active translation draft with conversational clarifications.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="intent.view.read",
        name="Intent View",
        category="intent",
        short_description="View the active translation draft summary and current handoff state.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="intent.clear.read",
        name="Intent Clear",
        category="intent",
        short_description="Archive and clear the active translation draft for the current chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.plan.read",
        name="Build Plan",
        category="planning",
        short_description="Generate a read-only build plan from the active translation draft.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.plan.view.read",
        name="Build Plan View",
        category="planning",
        short_description="View the active derived build plan for the current chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.plan.clear.read",
        name="Build Plan Clear",
        category="planning",
        short_description="Clear the active derived build plan for the current chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.step.read",
        name="Plan Step",
        category="planning",
        short_description="Propose the next actionable task group from the active build plan.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.step.approve.query",
        name="Plan Step Approve",
        category="planning",
        short_description="Approve the current plan proposal and route one step through the controlled execution path.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="external_side_effect",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="build.status.read",
        name="Plan Status",
        category="planning",
        short_description="View bridge progress for the active build plan.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.step.reset.read",
        name="Plan Step Reset",
        category="planning",
        short_description="Clear the current plan proposal without advancing the active plan.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.bundle.propose.read",
        name="Bundle Propose",
        category="planning",
        short_description="Propose a small bounded multi-step execution bundle from the active build plan.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.bundle.approve.query",
        name="Bundle Approve",
        category="planning",
        short_description="Approve the current bounded bundle and execute its approved steps sequentially.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="external_side_effect",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="build.bundle.status.read",
        name="Bundle Status",
        category="planning",
        short_description="View the current bounded bundle proposal or run state.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.bundle.cancel.query",
        name="Bundle Cancel",
        category="planning",
        short_description="Cancel the current bounded bundle without starting new work.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="build.bundle.reset.query",
        name="Bundle Reset",
        category="planning",
        short_description="Clear the current bounded bundle state after it stops or becomes stale.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="build.bootstrap.propose.read",
        name="Bootstrap Project",
        category="planning",
        short_description="Propose a bounded starter project scaffold from the active translation and build plan.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.bootstrap.view.read",
        name="Bootstrap View",
        category="planning",
        short_description="View the current bounded starter scaffold proposal or its latest result.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="project.generated.view.read",
        name="Generated Project View",
        category="planning",
        short_description="View the active isolated generated project target for the current Telegram chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.bootstrap.approve.query",
        name="Bootstrap Approve",
        category="planning",
        short_description="Explicitly approve a bounded starter scaffold and create its files through the existing file-create path.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="build.bootstrap.reset.query",
        name="Bootstrap Reset",
        category="planning",
        short_description="Clear the current bounded starter scaffold proposal for the current Telegram chat.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="mode.read",
        name="Mode",
        category="operator",
        short_description="Read the selected mode, policy, provider, and remote-use gate.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="models.read",
        name="Models",
        category="provider",
        short_description="List locally available Ollama models for offline use.",
        execution_type="read",
        provider_dependency="ollama",
        network_requirement="local",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="provider_query",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="ask.provider_query",
        name="Provider Ask",
        category="provider",
        short_description="Run a provider-backed ask through the active offline or online provider path.",
        execution_type="query",
        provider_dependency="active_provider",
        network_requirement="conditional",
        requires_runtime=True,
        requires_readiness=True,
        access_kind="external_side_effect",
        locality="hybrid",
        data_scope="provider_query",
        offline_safety="optional_online",
        confirmation_sensitivity="policy_based",
        telegram_exposure="allowed",
        policy_sensitivity="online_sensitive",
        supports_timeout=True,
        supports_confirmation=True,
        default_timeout_ms=18000,
        cooldown_sensitive=True,
        scope_type="network",
        access_mode="execute",
        scope_domain_allowlist=("api.openai.com", "127.0.0.1", "localhost"),
    ),
    CapabilityManifest(
        capability_id="audit.read",
        name="Audit",
        category="operator",
        short_description="Summarize recent capability executions from the in-memory audit log.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="workflow.read",
        name="Workflow Read",
        category="operator",
        short_description="Inspect recent workflows and the current workflow state for the current Telegram chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="workflow.cancel",
        name="Workflow Cancel",
        category="operator",
        short_description="Cancel an active workflow for the current Telegram chat.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="mutating",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        scope_type="internal",
        access_mode="write",
        include_in_capabilities_summary=True,
    ),
    CapabilityManifest(
        capability_id="repo.status.read",
        name="Repo Status",
        category="repository",
        short_description="Read branch, cleanliness, and recent commits from the configured repository.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="read_only",
        locality="local_only",
        data_scope="repository",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        scope_type="repository",
        access_mode="read",
        scope_uses_configured_root=True,
    ),
    CapabilityManifest(
        capability_id="file.read",
        name="File Read",
        category="filesystem",
        short_description="Read a bounded preview from a text file inside the configured allowed roots.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="read_only",
        locality="local_only",
        data_scope="file_system",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        scope_type="filesystem",
        access_mode="read",
        scope_uses_configured_paths=True,
    ),
    CapabilityManifest(
        capability_id="file.create.write",
        name="File Create",
        category="filesystem",
        short_description="Create one new text file inside the configured allowed roots after explicit confirmation.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="mutating",
        locality="local_only",
        data_scope="file_system",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_confirmation=True,
        scope_type="filesystem",
        access_mode="write",
        scope_uses_configured_paths=True,
    ),
    CapabilityManifest(
        capability_id="file.patch.write",
        name="File Patch",
        category="filesystem",
        short_description="Apply bounded text replacements to one existing file inside the configured allowed roots.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="mutating",
        locality="local_only",
        data_scope="file_system",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_confirmation=True,
        scope_type="filesystem",
        access_mode="write",
        scope_uses_configured_paths=True,
    ),
    CapabilityManifest(
        capability_id="file.write.replace",
        name="File Replace",
        category="filesystem",
        short_description="Replace one existing text file inside the configured allowed roots after explicit confirmation.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="mutating",
        locality="local_only",
        data_scope="file_system",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_confirmation=True,
        scope_type="filesystem",
        access_mode="write",
        scope_uses_configured_paths=True,
    ),
    CapabilityManifest(
        capability_id="shell.command.run",
        name="Run Command",
        category="repository",
        short_description="Run a bounded local development command inside the configured repository root after explicit confirmation.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="external_side_effect",
        locality="local_only",
        data_scope="repository",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_timeout=True,
        supports_confirmation=True,
        default_timeout_ms=20000,
        scope_type="repository",
        access_mode="execute",
        scope_uses_configured_root=True,
    ),
    CapabilityManifest(
        capability_id="test.command.run",
        name="Test Command",
        category="repository",
        short_description="Run a bounded local test command inside the configured repository root after explicit confirmation.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="external_side_effect",
        locality="local_only",
        data_scope="repository",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_timeout=True,
        supports_confirmation=True,
        default_timeout_ms=20000,
        scope_type="repository",
        access_mode="execute",
        scope_uses_configured_root=True,
    ),
    CapabilityManifest(
        capability_id="web.fetch.read",
        name="Web Fetch",
        category="web",
        short_description="Fetch a bounded preview from an allowlisted public web URL.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="remote",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="read_only",
        locality="networked",
        data_scope="web",
        offline_safety="requires_online",
        confirmation_sensitivity="policy_based",
        telegram_exposure="allowed",
        policy_sensitivity="online_sensitive",
        supports_timeout=True,
        supports_confirmation=True,
        default_timeout_ms=8000,
        scope_type="network",
        access_mode="read",
        scope_uses_configured_domains=True,
    ),
    CapabilityManifest(
        capability_id="build.feature.status.read",
        name="Feature Bundle Status",
        category="operator",
        short_description="Inspect the active bounded multi-file feature bundle for the current chat.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
    CapabilityManifest(
        capability_id="build.feature.apply.query",
        name="Feature Bundle Apply",
        category="filesystem",
        short_description="Request explicit approval to apply the active bounded multi-file feature bundle.",
        execution_type="query",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=True,
        access_kind="mutating",
        locality="local_only",
        data_scope="file_system",
        offline_safety="safe_offline",
        confirmation_sensitivity="always",
        telegram_exposure="allowed",
        supports_confirmation=True,
        scope_type="internal",
        access_mode="write",
    ),
    CapabilityManifest(
        capability_id="capabilities.read",
        name="Capabilities",
        category="operator",
        short_description="Summarize visible capability state and trust boundaries.",
        execution_type="read",
        provider_dependency="none",
        network_requirement="none",
        requires_runtime=False,
        requires_readiness=False,
        access_kind="read_only",
        locality="local_only",
        data_scope="internal_state",
        offline_safety="safe_offline",
        confirmation_sensitivity="never",
        telegram_exposure="allowed",
        supports_degraded_mode=True,
    ),
)

CAPABILITY_DEFINITIONS = CAPABILITY_MANIFESTS

COMMAND_CAPABILITY_MAP: dict[str, str] = {
    "/help": "help.read",
    "/startruntime": "runtime.activate.query",
    "/nodes": "nodes.read",
    "/nodeview": "node.view.read",
    "/nodeselect": "node.select.query",
    "/nodeclear": "node.clear.query",
    "/status": "status.read",
    "/lastaction": "action.last.read",
    "/chat": "chat.orchestrate.read",
    "/translate": "intent.translate.read",
    "/refine": "intent.refine.read",
    "/translateview": "intent.view.read",
    "/translateclear": "intent.clear.read",
    "/planbuild": "build.plan.read",
    "/planstep": "build.step.read",
    "/planapprove": "build.step.approve.query",
    "/planstatus": "build.status.read",
    "/planresetstep": "build.step.reset.read",
    "/planstepbundle": "build.bundle.propose.read",
    "/bundleapprove": "build.bundle.approve.query",
    "/bundlestatus": "build.bundle.status.read",
    "/bundlecancel": "build.bundle.cancel.query",
    "/bundlereset": "build.bundle.reset.query",
    "/planview": "build.plan.view.read",
    "/planclear": "build.plan.clear.read",
    "/bootstrapproject": "build.bootstrap.propose.read",
    "/bootstrapview": "build.bootstrap.view.read",
    "/bootstrapapprove": "build.bootstrap.approve.query",
    "/bootstrapreset": "build.bootstrap.reset.query",
    "/projectview": "project.generated.view.read",
    "/mode": "mode.read",
    "/models": "models.read",
    "/repo": "repo.status.read",
    "/file": "file.read",
    "/createfile": "file.create.write",
    "/patchlast": "file.patch.write",
    "/patchfile": "file.patch.write",
    "/writefile": "file.write.replace",
    "/featurestatus": "build.feature.status.read",
    "/featureapply": "build.feature.apply.query",
    "/run": "shell.command.run",
    "/test": "test.command.run",
    "/web": "web.fetch.read",
    "/contexts": "context.read",
    "/clearcontext": "context.clear",
    "/workflows": "workflow.read",
    "/workflowstatus": "workflow.read",
    "/cancelworkflow": "workflow.cancel",
    "/ask": "ask.provider_query",
    "/askd": "ask.provider_query",
    "/asklast": "ask.provider_query",
    "/askctx": "ask.provider_query",
    "/audit": "audit.read",
    "/capabilities": "capabilities.read",
}


def validate_capability_manifests(manifests: tuple[CapabilityManifest, ...] | list[CapabilityManifest]) -> tuple[str, ...]:
    seen_ids: set[str] = set()
    issues: list[str] = []
    for manifest in manifests:
        if not manifest.capability_id.strip():
            issues.append("Capability manifest is missing capability_id.")
        if not manifest.name.strip():
            issues.append(f"{manifest.capability_id or '<unknown>'}: name is required.")
        if not manifest.category:
            issues.append(f"{manifest.capability_id or '<unknown>'}: category is required.")
        if not manifest.short_description.strip():
            issues.append(f"{manifest.capability_id or '<unknown>'}: short_description is required.")
        if manifest.capability_id in seen_ids:
            issues.append(f"{manifest.capability_id}: duplicate capability_id.")
        seen_ids.add(manifest.capability_id)

        if manifest.default_timeout_ms < 0:
            issues.append(f"{manifest.capability_id}: default_timeout_ms cannot be negative.")
        if manifest.default_timeout_ms and not manifest.supports_timeout:
            issues.append(f"{manifest.capability_id}: default_timeout_ms requires supports_timeout.")
        if manifest.confirmation_sensitivity != "never" and not manifest.supports_confirmation:
            issues.append(f"{manifest.capability_id}: confirmation_sensitivity requires supports_confirmation.")
        if manifest.locality == "local_only" and manifest.offline_safety == "requires_online":
            issues.append(f"{manifest.capability_id}: local_only capability cannot require online execution.")
        if manifest.provider_dependency == "ollama" and manifest.offline_safety == "requires_online":
            issues.append(f"{manifest.capability_id}: Ollama-dependent capability cannot be requires_online.")
        if manifest.access_kind != "read_only" and manifest.execution_type == "read":
            issues.append(f"{manifest.capability_id}: non-read-only capability cannot use execution_type='read'.")
        if manifest.telegram_exposure == "denied" and manifest.include_in_capabilities_summary:
            issues.append(f"{manifest.capability_id}: telegram_exposure='denied' cannot be summary-visible.")
        if manifest.scope_type == "internal" and manifest.access_mode == "execute":
            issues.append(f"{manifest.capability_id}: internal scope cannot use execute access mode.")
        if manifest.scope_type == "internal" and (
            manifest.scope_allowed_paths
            or manifest.scope_domain_allowlist
            or manifest.scope_repo_root
            or manifest.scope_uses_configured_root
            or manifest.scope_uses_configured_paths
            or manifest.scope_uses_configured_domains
        ):
            issues.append(f"{manifest.capability_id}: internal scope cannot define filesystem, repository, or domain targets.")
        if manifest.scope_type == "filesystem" and not (manifest.scope_allowed_paths or manifest.scope_uses_configured_paths):
            issues.append(f"{manifest.capability_id}: filesystem scope requires scope_allowed_paths or configured-path binding.")
        if manifest.scope_type == "repository" and not (manifest.scope_repo_root or manifest.scope_uses_configured_root):
            issues.append(f"{manifest.capability_id}: repository scope requires scope_repo_root or configured-root binding.")
        if manifest.scope_type == "network" and not (manifest.scope_domain_allowlist or manifest.scope_uses_configured_domains):
            issues.append(f"{manifest.capability_id}: network scope requires scope_domain_allowlist or configured-domain binding.")
        if manifest.scope_uses_configured_root and manifest.scope_type != "repository":
            issues.append(f"{manifest.capability_id}: configured-root binding currently supports repository scope only.")
        if manifest.scope_uses_configured_paths and manifest.scope_type != "filesystem":
            issues.append(f"{manifest.capability_id}: configured-path binding currently supports filesystem scope only.")
        if manifest.scope_uses_configured_domains and manifest.scope_type != "network":
            issues.append(f"{manifest.capability_id}: configured-domain binding currently supports network scope only.")
    return tuple(issues)


def build_capability_registry(manifests: tuple[CapabilityManifest, ...] | list[CapabilityManifest]) -> dict[str, CapabilityManifest]:
    issues = validate_capability_manifests(manifests)
    if issues:
        raise CapabilityManifestError("Invalid capability manifests: " + "; ".join(issues))
    return {manifest.capability_id: manifest for manifest in manifests}


def get_capability_manifest(capability_id: str) -> CapabilityManifest:
    return CAPABILITY_REGISTRY[capability_id]


def list_summary_capabilities() -> tuple[CapabilityManifest, ...]:
    return tuple(
        manifest
        for manifest in CAPABILITY_MANIFESTS
        if manifest.user_visible and manifest.include_in_capabilities_summary
    )


CAPABILITY_REGISTRY = build_capability_registry(CAPABILITY_MANIFESTS)
