import { createAutonomousWorkSession } from "./autonomousWorkSession";
import { createAutonomousDeliveryPackage, createAutonomousReviewPackage, createAutonomousWorkItem, createAutonomousWorkItemPolicyFeedback } from "./autonomousWorkPlanning";
import { createAutonomousSessionRecord, createAutonomousSessionRegistry } from "./autonomousSessionRegistry";
import { buildRecoveryReport } from "./failureRecoveryIntelligence";
import { createMultiSessionSchedulerState } from "./multiSessionScheduler";
import { createGoalQueue, createGoalRecord } from "./multiGoalOrchestrator";
import { createMetaIntelligenceSummaryPackage } from "./metaIntelligenceSummary";
import { buildMetaIntelligenceState, detectMetaPatterns } from "./metaPatternDetector";
import { deriveMetaPolicyState, recommendMetaPolicyAdjustments } from "./metaPolicyRecommender";
import { buildOperatorDashboardState, type OperatorDashboardState } from "./operatorDashboardState";
import { buildRuntimeResult } from "./sessionRuntime";
import { scoreStrategyPortfolio } from "./strategyPortfolioScorer";
import { createStrategySummary } from "./strategySummary";
import { createInitialConversationalSession } from "./conversationalSessionState";

const DEMO_TIMESTAMP = "2026-04-26T12:00:00.000Z";

export function createOperatorDashboardDemoState(): OperatorDashboardState {
  const goalQueue = createGoalQueue([
    createGoalRecord({
      id: "stabilize-kbm-input",
      description: "Stabilize KBM input lane",
      priority: "high",
      status: "active",
      created_at: "2026-04-26T11:40:00.000Z",
      last_updated_at: "2026-04-26T11:58:00.000Z",
    }),
    createGoalRecord({
      id: "audit-reload-window",
      description: "Audit reload window timing",
      priority: "medium",
      status: "pending",
      created_at: "2026-04-26T11:45:00.000Z",
      last_updated_at: "2026-04-26T11:56:00.000Z",
    }),
    createGoalRecord({
      id: "verify-grenade-lane",
      description: "Verify grenade launch lane",
      priority: "high",
      status: "pending",
      created_at: "2026-04-26T11:46:00.000Z",
      last_updated_at: "2026-04-26T11:57:00.000Z",
      depends_on_goal_ids: ["stabilize-kbm-input"],
    }),
  ]);

  const approvalSession = createAutonomousWorkSession({
    operatorGoal: "Renew approval for bounded runtime handoff",
    createdAt: "2026-04-26T11:52:00.000Z",
    sessionApproval: false,
    chainInput: {
      maxSteps: 1,
      requestedSteps: [
        {
          title: "Renew approval",
          plannerReadyRequest: "Renew approval",
          requiredGate: "controlled_validation",
          validationRequired: true,
          commitAllowed: false,
          pushAllowed: false,
          stopOnFailure: true,
        },
      ],
    },
  });

  const recoveryReport = buildRecoveryReport({
    created_at: "2026-04-26T11:59:00.000Z",
    source: "controlled_validation",
    status: "validation_failed",
    message: "The expected grenade telemetry file was not written.",
    failures: [
      {
        code: "missing_file",
        message: "Expected grenade telemetry file is missing.",
        file_path: "Logs/grenade-lane.json",
      },
    ],
    validation_status: "validation_failed",
    validation_recommendation: "review_required",
  });

  const autonomousSessionRegistry = createAutonomousSessionRegistry({
    runtime_id: "demo-runtime",
    created_at: "2026-04-26T11:54:00.000Z",
    updated_at: "2026-04-26T11:59:00.000Z",
    global_tick_budget: 8,
    sessions: [
      createAutonomousSessionRecord({
        session_id: "demo-session-feature-ui",
        runtime_id: "demo-runtime",
        session_type: "feature",
        priority: "high",
        status: "running",
        allocated_resources: { logical_cpu_units: 2, tick_budget: 5, chain_slots: 2, agent_assignments_allowed: 2 },
        active_chain_ids: ["chain-ui-runtime"],
        queued_work_item_ids: ["demo-work-proof-summary"],
        assigned_agent_ids: ["planner-agent", "reporter-agent"],
        start_time: "2026-04-26T11:54:00.000Z",
        last_tick: "2026-04-26T11:58:00.000Z",
        coordination_group_id: "demo-group-ui",
      }),
      createAutonomousSessionRecord({
        session_id: "demo-session-bugfix-delivery",
        runtime_id: "demo-runtime",
        session_type: "bugfix",
        priority: "medium",
        status: "pending",
        allocated_resources: { logical_cpu_units: 1, tick_budget: 4, chain_slots: 1, agent_assignments_allowed: 1 },
        active_chain_ids: ["chain-delivery-proof"],
        queued_work_item_ids: ["demo-work-risky-refactor"],
        assigned_agent_ids: ["validator-agent"],
        start_time: "2026-04-26T11:56:00.000Z",
        coordination_group_id: "demo-group-ui",
        parent_session_id: "demo-session-feature-ui",
      }),
    ],
  });

  const state = buildOperatorDashboardState({
    goal_queue: goalQueue,
    runtime_result: buildRuntimeResult(approvalSession),
    recovery_reports: [recoveryReport],
    autonomous_work_items: [
      createAutonomousWorkItem({
        work_item_id: "demo-work-proof-summary",
        title: "Package overnight proof findings",
        summary: "Prepare a concise review packet from the latest overnight proof run.",
        source: "planner-demo",
        proposed_by_agent_id: "planner-agent",
        priority: "medium",
        risk_level: "low",
        estimated_tick_cost: 2,
        required_agent_roles: ["reporter"],
        required_approval_level: "none",
        dependency_ids: [],
        expected_outputs: ["proof-summary.md"],
        safety_scope: "bounded_runtime_only",
        status: "approved_for_planning",
        created_at: "2026-04-26T11:55:00.000Z",
        updated_at: "2026-04-26T11:58:00.000Z",
      }),
      createAutonomousWorkItem({
        work_item_id: "demo-work-risky-refactor",
        title: "Refactor runtime scoring heuristic",
        summary: "High-risk planning work that still requires operator approval.",
        source: "planner-demo",
        proposed_by_agent_id: "planner-agent",
        priority: "high",
        risk_level: "high",
        estimated_tick_cost: 5,
        required_agent_roles: ["planner", "validator"],
        required_approval_level: "operator_approval",
        dependency_ids: [],
        expected_outputs: ["scoring-plan.md"],
        safety_scope: "bounded_multi_agent_runtime",
        status: "proposed",
        created_at: "2026-04-26T11:56:00.000Z",
        updated_at: "2026-04-26T11:59:00.000Z",
      }),
    ],
    review_packages: [
      createAutonomousReviewPackage({
        package_id: "demo-review-package",
        work_item_id: "demo-work-proof-summary",
        chain_id: "demo-chain-proof-summary",
        status: "pending",
        summary: "A bounded proof summary is ready for operator decision.",
        files_changed: ["web/lib/aie/operatorDashboardState.ts"],
        tests_run: ["npm run test:trace:safe"],
        proof_results: ["proof:overnight-autonomy:safe -> proof_passed"],
        risks: ["No runtime mutation changes"],
        recommended_decision: "open_pr",
        rollback_notes: "Review artifact only; no rollback required.",
        operator_actions: ["approve", "reject", "defer", "request_changes", "open_pr", "archive"],
      }),
      createAutonomousReviewPackage({
        package_id: "demo-unity-review-preview",
        work_item_id: "unity-validation-demo-preview",
        chain_id: "demo-unity-validation-chain",
        status: "approved",
        summary: "Demo preview: Unity validation preview was not executed. Adapter remains non-mutating and review-gated.",
        files_changed: [],
        tests_run: ["unity read-only validation probe"],
        proof_results: [
          "Execution kind: adapter_preview",
          "Scene validation status: not_checked",
          "Checked scene name: CastleHub",
          "Missing script count: unknown",
          "Console error count: unknown",
          "Object count: unknown",
          `Evidence timestamp: ${DEMO_TIMESTAMP}`,
          "Recommended next operator action: request operator approval before live Unity endpoint verification",
        ],
        risks: ["Demo preview only. No Unity or project mutation path enabled."],
        recommended_decision: "approve",
        rollback_notes: "Demo preview evidence only; no rollback required.",
        operator_actions: ["approve", "archive"],
      }),
      createAutonomousReviewPackage({
        package_id: "demo-unity-mutation-review-preview",
        work_item_id: "unity-mutation-preview-demo-preview",
        chain_id: "demo-unity-mutation-preview-chain",
        status: "approved",
        summary: "DRY RUN ONLY: Unity scene object creation preview for CheckpointAnchor in EnemyAIDemo. NOT EXECUTED.",
        files_changed: [],
        tests_run: ["unity scene object creation dry-run preview"],
        proof_results: [
          "Execution kind: dry_run_preview",
          "Requested object name: CheckpointAnchor",
          "Target scene: EnemyAIDemo",
          "Intended components: Transform, BoxCollider",
          "Intended transform position: 4, 1, 0",
          "Intended transform rotation: 0, 0, 0",
          "Intended transform scale: 1, 1, 1",
          "Risk level: medium",
          "Dry run: true",
          "Executed: false",
          "Final execution required: true",
          "Final execution authorized: false",
          "Final execution authorization status: FINAL EXECUTION NOT AUTHORIZED",
          "Required approval gate: operator planning approval",
          "Required approval gate: review package approval",
          "Required approval gate: operator approval",
          "Required approval gate: dry-run preview approval",
          "Required approval gate: explicit final execute gate",
          "Recommended next operator action: Keep the final execute gate disabled until a future reviewed mutation path exists.",
        ],
        risks: ["DRY RUN ONLY", "NOT EXECUTED", "FINAL EXECUTION NOT AUTHORIZED", "Demo preview only. No Unity scene mutation path enabled."],
        recommended_decision: "approve",
        rollback_notes: "Dry-run mutation preview only; no rollback required.",
        operator_actions: ["approve", "archive"],
      }),
    ],
    delivery_packages: [
      createAutonomousDeliveryPackage({
        delivery_package_id: "delivery-demo-review-package-approved",
        review_package_id: "demo-review-package-approved",
        work_item_id: "demo-work-delivery-ready",
        chain_id: "demo-chain-delivery-ready",
        branch_name: "autonomy/demo-work-delivery-ready",
        commit_plan: [
          "Stage the approved operator dashboard delivery patch.",
          "Run validation evidence capture before commit approval.",
          "Prepare the PR summary and rollback notes for operator signoff.",
        ],
        files_changed: ["web/app/operator/OperatorDashboardClient.tsx", "web/lib/aie/operatorControlSurface.ts"],
        validation_results: ["npm run test:trace:safe"],
        proof_results: ["proof:autonomous-planning:safe -> proof_passed"],
        risk_summary: "UI handoff still requires operator confirmation before commit.",
        rollback_plan: "Revert the operator dashboard delivery patch and restore the last approved runtime handoff state.",
        release_notes: "Delivery-ready package with validation evidence and rollback notes.",
        recommended_pr_title: "AI-E: deliver demo-work-delivery-ready",
        recommended_pr_body: "Summary: Delivery-ready operator dashboard patch.\n\nValidation evidence: npm run test:trace:safe\n\nProof evidence: proof:autonomous-planning:safe -> proof_passed\n\nRollback notes: Revert the operator dashboard delivery patch and restore the last approved runtime handoff state.",
        operator_decision: null,
        status: "awaiting_operator_approval",
        created_at: "2026-04-26T11:58:00.000Z",
        updated_at: "2026-04-26T11:59:00.000Z",
      }),
      createAutonomousDeliveryPackage({
        delivery_package_id: "demo-unity-delivery-preview",
        review_package_id: "demo-unity-review-preview",
        work_item_id: "unity-validation-demo-preview",
        chain_id: "demo-unity-validation-chain",
        branch_name: "",
        commit_plan: [
          "Keep Unity validation evidence attached to the reviewed delivery lane.",
          "Do not mutate scenes, prefabs, assets, or scripts from this delivery artifact.",
        ],
        files_changed: [],
        validation_results: [
          "Execution kind: adapter_preview",
          "Bridge status: adapter_preview",
          "Scene validation status: not_checked",
          "Checked scene name: CastleHub",
          "Missing script count: unknown",
          "Console error count: unknown",
          "Object count: unknown",
          `Evidence timestamp: ${DEMO_TIMESTAMP}`,
          "Recommended next operator action: request operator approval before live Unity endpoint verification",
        ],
        proof_results: ["adapter_preview"],
        risk_summary: "Demo preview only. No mutation path enabled.",
        rollback_plan: "Discard the demo preview package if it is no longer useful.",
        release_notes: "Demo preview: Unity validation preview was not executed. Adapter remains non-mutating and review-gated.",
        recommended_pr_title: "",
        recommended_pr_body: "Unity validation evidence handoff\n\nSummary: Demo preview only.\n\nNext operator action: request operator approval before live Unity endpoint verification",
        operator_decision: null,
        status: "awaiting_operator_approval",
        created_at: DEMO_TIMESTAMP,
        updated_at: DEMO_TIMESTAMP,
      }),
      createAutonomousDeliveryPackage({
        delivery_package_id: "demo-unity-mutation-delivery-preview",
        review_package_id: "demo-unity-mutation-review-preview",
        work_item_id: "unity-mutation-preview-demo-preview",
        chain_id: "demo-unity-mutation-preview-chain",
        branch_name: "",
        commit_plan: [
          "Keep the Unity mutation preview attached to the reviewed delivery lane.",
          "DRY RUN ONLY: do not create, spawn, or write any Unity scene object from this package.",
          "Require the explicit final execute gate before any future mutation path is allowed.",
        ],
        files_changed: [],
        validation_results: [
          "Execution kind: dry_run_preview",
          "Requested object name: CheckpointAnchor",
          "Target scene: EnemyAIDemo",
          "Intended components: Transform, BoxCollider",
          "Intended transform position: 4, 1, 0",
          "Intended transform rotation: 0, 0, 0",
          "Intended transform scale: 1, 1, 1",
          "Risk level: medium",
          "Dry run: true",
          "Executed: false",
          "Final execution required: true",
          "Final execution authorized: false",
          "Final execution authorization status: FINAL EXECUTION NOT AUTHORIZED",
          "Required approval gate: operator planning approval",
          "Required approval gate: review package approval",
          "Required approval gate: operator approval",
          "Required approval gate: dry-run preview approval",
          "Required approval gate: explicit final execute gate",
          "Recommended next operator action: Keep the final execute gate disabled until a future reviewed mutation path exists.",
        ],
        proof_results: ["dry_run_preview", "DRY RUN ONLY", "NOT EXECUTED"],
        risk_summary: "Dry-run Unity mutation preview only. Final execution not authorized. No mutation path enabled.",
        rollback_plan: "Discard the dry-run mutation preview package if it is no longer useful.",
        release_notes: "DRY RUN ONLY: Unity scene object creation preview for CheckpointAnchor in EnemyAIDemo. NOT EXECUTED.",
        recommended_pr_title: "",
        recommended_pr_body: "Unity mutation preview handoff\n\nSummary: DRY RUN ONLY.\n\nNext operator action: Keep the final execute gate disabled until a future reviewed mutation path exists.",
        operator_decision: null,
        status: "awaiting_operator_approval",
        created_at: DEMO_TIMESTAMP,
        updated_at: DEMO_TIMESTAMP,
      }),
    ],
    planning_policy_feedback: createAutonomousWorkItemPolicyFeedback({ approvals_recorded: 2, deferrals_recorded: 1 }),
    planning_budget: 3,
    autonomous_session_registry: autonomousSessionRegistry,
    autonomous_session_scheduler: createMultiSessionSchedulerState({
      global_tick_budget: 8,
      global_ticks_consumed: 2,
      per_session_ticks: {
        "demo-session-feature-ui": 2,
        "demo-session-bugfix-delivery": 1,
      },
    }),
    session_resource_allocator_config: {
      max_logical_cpu_units: 6,
      max_concurrent_chains: 4,
      max_chains_per_session: 2,
    },
    session_file_targets: {
      "demo-session-feature-ui": ["web/app/operator/OperatorDashboardClient.tsx"],
      "demo-session-bugfix-delivery": ["web/app/operator/OperatorDashboardClient.tsx"],
    },
    session_goal_targets: {
      "demo-session-feature-ui": ["goal-operator-dashboard"],
      "demo-session-bugfix-delivery": ["goal-operator-dashboard"],
    },
    session_coordinator: {
      groups: [{ coordination_group_id: "demo-group-ui", session_ids: ["demo-session-feature-ui", "demo-session-bugfix-delivery"], status: "active", shared_goal: "Operator dashboard handoff" }],
      dependencies: [{ source_session_id: "demo-session-feature-ui", target_session_id: "demo-session-bugfix-delivery", relationship: "unlocks", status: "pending", reason: "Bugfix session waits for the feature session to stabilize the dashboard lane." }],
    },
    generated_at: DEMO_TIMESTAMP,
  });

  state.meta_operator_decision_history = [];
  state.meta_policy_state = deriveMetaPolicyState(state);
  state.meta_detected_patterns = detectMetaPatterns({
    studio_operations_state: state.studio_operations,
    runtime_timeline_events: state.runtime_observability?.event_log,
    execution_chains: state.execution_chains,
    review_packages: state.review_packages,
    delivery_packages: state.delivery_packages,
    recovery_events: state.recovery_recommendations,
    operator_decisions: state.meta_operator_decision_history,
    autonomous_sessions: state.governed_runtime_lanes,
    agent_runtime: state.agent_runtime,
  });
  state.meta_policy_recommendations = recommendMetaPolicyAdjustments({
    detected_patterns: state.meta_detected_patterns,
    current_policy_state: state.meta_policy_state,
    overnight_policy: state.supervised_session?.overnight_policy,
    recovery_policy: state.supervised_session?.recovery_policy ?? null,
    planning_priority_weights: (state.planning_recommendations ?? []).map((item) => `${item.work_item_id}:${item.score}`),
    delivery_gating_rules: (state.delivery_packages ?? []).map((item) => `${item.delivery_package_id}:${item.status}`),
    operator_decision_history: state.meta_operator_decision_history,
    timestamp: state.last_updated_at,
  });
  state.meta_intelligence = buildMetaIntelligenceState(state, state.meta_detected_patterns, state.meta_policy_recommendations);
  state.meta_summary_package = createMetaIntelligenceSummaryPackage(state, state.last_updated_at);
  state.strategy_goals = [
    {
      strategy_goal_id: "strategy-ship-first-playable-loop",
      title: "Ship first playable studio loop",
      summary: "Prioritize the playable studio loop that proves AI-E can coordinate a bounded milestone from strategy through delivery.",
      category: "product",
      priority: "high",
      impact_score: 92,
      effort_score: 56,
      risk_score: 34,
      confidence_score: 79,
      time_horizon: "near_term",
      status: "approved",
      owner_agent_role: "planner",
      dependency_goal_ids: [],
      blocked_by: [],
      success_criteria: ["Playable loop milestone approved", "Delivery package reaches operator-ready state"],
      expected_outputs: ["playable-loop-brief.md", "milestone-proof.json"],
      linked_work_item_ids: ["demo-work-proof-summary"],
      linked_delivery_package_ids: ["delivery-demo-review-package-approved"],
      created_at: "2026-04-26T11:45:00.000Z",
      updated_at: "2026-04-26T11:58:00.000Z",
    },
    {
      strategy_goal_id: "strategy-harden-runtime-observability",
      title: "Harden runtime observability",
      summary: "Improve operator visibility into bounded autonomy health, proof coverage, and recovery signals.",
      category: "operations",
      priority: "high",
      impact_score: 78,
      effort_score: 44,
      risk_score: 28,
      confidence_score: 81,
      time_horizon: "quarterly",
      status: "active",
      owner_agent_role: "reporter",
      dependency_goal_ids: [],
      blocked_by: [],
      success_criteria: ["Runtime introspection exposes the current risk lane", "Operator summary package stays current"],
      expected_outputs: ["observability-gap-report.md"],
      linked_work_item_ids: ["demo-work-proof-summary"],
      linked_delivery_package_ids: [],
      created_at: "2026-04-26T11:46:00.000Z",
      updated_at: "2026-04-26T11:59:00.000Z",
    },
    {
      strategy_goal_id: "strategy-expand-creator-templates",
      title: "Expand creator template coverage",
      summary: "Prepare a lower-risk tooling strategy that expands reusable creator templates for studio teams.",
      category: "tooling",
      priority: "medium",
      impact_score: 64,
      effort_score: 30,
      risk_score: 18,
      confidence_score: 73,
      time_horizon: "quarterly",
      status: "proposed",
      owner_agent_role: "planner",
      dependency_goal_ids: [],
      blocked_by: [],
      success_criteria: ["Template inventory approved", "Template gaps mapped to current work lanes"],
      expected_outputs: ["creator-template-coverage.md"],
      linked_work_item_ids: [],
      linked_delivery_package_ids: [],
      created_at: "2026-04-26T11:46:30.000Z",
      updated_at: "2026-04-26T11:58:30.000Z",
    },
    {
      strategy_goal_id: "strategy-evaluate-live-ops-experiment",
      title: "Evaluate live-ops experiment",
      summary: "Assess a higher-risk live-ops idea without activating it until confidence improves.",
      category: "monetization",
      priority: "medium",
      impact_score: 74,
      effort_score: 52,
      risk_score: 76,
      confidence_score: 39,
      time_horizon: "long_term",
      status: "blocked",
      owner_agent_role: "planner",
      dependency_goal_ids: ["strategy-ship-first-playable-loop"],
      blocked_by: ["Needs clearer confidence from recent meta patterns", "Depends on first playable loop milestone"],
      success_criteria: ["Risk review approved", "Experiment remains bounded and operator-gated"],
      expected_outputs: ["live-ops-experiment-review.md"],
      linked_work_item_ids: [],
      linked_delivery_package_ids: [],
      created_at: "2026-04-26T11:47:00.000Z",
      updated_at: "2026-04-26T11:57:00.000Z",
    },
  ];
  state.strategy_decision_history = [];
  state.strategy_decompositions = [];
  state.strategy_portfolio_scores = scoreStrategyPortfolio({
    goals: state.strategy_goals,
    state,
    operator_preferences: (state.meta_policy_recommendations ?? []).map((item) => item.target),
  });
  state.strategy_summary_package = createStrategySummary(state, state.last_updated_at);
  state.conversational_session = createInitialConversationalSession(DEMO_TIMESTAMP);
  return state;
}

export async function loadOperatorDashboardState(): Promise<OperatorDashboardState> {
  return createOperatorDashboardDemoState();
}