// AI-E SANDBOX GAMEPLAY FEATURE PATCH ADAPTER (EXEC-0052-G)
//
// First governed gameplay feature patch implementation.
// Generates and injects sandboxGameplayFeaturePatch.cs with deterministic helpers.
//
// Feature: Stamina Regeneration Clamp
// Injects StaminaHelper.ClampStaminaRegeneration() static method.
// Ensures stamina values stay within valid bounds during regeneration.
//
// Each invocation:
//   - Creates or updates sandboxGameplayFeaturePatch.cs
//   - Injects deterministic C# helper method
//   - Increments version counter in metadata
//   - Records lastPatch timestamp
//
// Lifecycle: queued → authorization_verified → dispatching → running → completed
// stdout: injected method + diff summary
//
// NO child_process. NO shell. NO network. NO production mutation.
// Sandbox-scoped read+write only. Single C# file. Human authority final.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";

import {
  advanceLifecycleState,
  createRuntimeExecutionLifecycle,
  makeFailedInvocationResult,
  makeOutputCapture,
  makeRuntimeAdapterSafetyBoundary,
  makeRuntimeFailure,
  type GovernedRuntimeAdapter,
  type GovernedRuntimeAdapterCapability,
  type GovernedRuntimeAdapterId,
  type GovernedRuntimeInvocation,
  type RuntimeInvocationResult,
} from "./governedRuntimeAdapterContract";

// =====================================================================================
// ADAPTER CONSTANTS
// =====================================================================================

export const SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID = "openclaw-sandbox-gameplay-feature-patch-v1" as GovernedRuntimeAdapterId;
export const SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_VERSION = "EXEC-0052-G";
export const SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME = "sandboxGameplayFeaturePatch.cs";

const MAX_STDOUT_BYTES = 65_536;
const MAX_STDERR_BYTES = 8_192;
const DEFAULT_TIMEOUT_MS = 30_000;
const MAX_PATCH_LABEL_LENGTH = 80;

// =====================================================================================
// FILE SYSTEM CONTRACT
// =====================================================================================

export type SandboxGameplayFeaturePatchFilesystem = {
  createDirectory: (absolutePath: string) => Promise<void>;
  writeFile: (absolutePath: string, content: string) => Promise<void>;
  readFile: (absolutePath: string) => Promise<string | null>;
};

// =====================================================================================
// ADAPTER CAPABILITY
// =====================================================================================

const SANDBOX_GAMEPLAY_FEATURE_PATCH_CAPABILITY: GovernedRuntimeAdapterCapability = {
  runtimeType: "openclaw",
  supportedCapabilities: ["patch_preview"],
  requiresSandbox: true,
  requiresApproval: true,
  shellExecutionEnabled: false,
  networkExecutionEnabled: false,
  productionMutationEnabled: false,
};

// =====================================================================================
// HELPERS: BOUNDARY CHECKING
// =====================================================================================

function isWithinWorkspace(workspaceRoot: string, targetPath: string): boolean {
  const resolved = path.resolve(targetPath);
  const workspaceResolved = path.resolve(workspaceRoot);
  return resolved.startsWith(workspaceResolved + path.sep) || resolved === workspaceResolved;
}

// =====================================================================================
// HELPERS: C# CODE GENERATION
// =====================================================================================

function generateStaminaHelperMethod(patchVersion: number): string {
  return `/// <summary>
/// Feature Patch: Stamina Regeneration Clamp (EXEC-0052-G)
/// Version: ${patchVersion}
/// Injects deterministic stamina bounds validation during regeneration.
/// </summary>
public static class StaminaHelper
{
    private const float MIN_STAMINA = 0f;

    /// <summary>
    /// Clamps stamina regeneration to valid bounds.
    /// Ensures currentStamina + regenAmount stays within [MIN_STAMINA, maxStamina].
    /// </summary>
    public static float ClampStaminaRegeneration(
        float currentStamina,
        float maxStamina,
        float regenAmount)
    {
        if (maxStamina <= 0f)
            return currentStamina;

        float targetValue = currentStamina + regenAmount;
        return Mathf.Clamp(targetValue, MIN_STAMINA, maxStamina);
    }
}`;
}

function generateFileContent(patchVersion: number, lastPatchLabel: string): string {
  const timestamp = new Date().toISOString();
  return `// SANDBOX-ONLY GAMEPLAY FEATURE PATCH FILE
// Generated by: AI-E Governed Sandbox (EXEC-0052-G)
// Timestamp: ${timestamp}
// Patch Version: ${patchVersion}
// Last Patch: ${lastPatchLabel}
//
// This file is sandbox-only and not for production use.
// Contains deterministic gameplay helper methods.
// Rollback-ready: deletable without side effects.

using UnityEngine;
using System;

#pragma warning disable CS0414 // assigned but not used
#pragma warning disable CS0618 // obsolete

namespace AI_E.Sandbox
{
${generateStaminaHelperMethod(patchVersion)}
}`;
}

// =====================================================================================
// FACTORY
// =====================================================================================

function resolveAdapterFilesystem(input?: SandboxGameplayFeaturePatchFilesystem): Required<SandboxGameplayFeaturePatchFilesystem> {
  return {
    createDirectory: input?.createDirectory ?? ((p) => mkdir(p, { recursive: true }).then(() => undefined)),
    writeFile: input?.writeFile ?? ((p, c) => writeFile(p, c, "utf8")),
    readFile: input?.readFile ?? (async (p) => {
      try {
        const content = await readFile(p, "utf8");
        return content;
      } catch (e: unknown) {
        if (
          typeof e === "object" && e !== null && "code" in e &&
          (e as { code: string }).code === "ENOENT"
        ) {
          return null;
        }
        throw e;
      }
    }),
  };
}

// =====================================================================================
// ADAPTER EXPORT
// =====================================================================================

export function createSandboxGameplayFeaturePatchAdapter(
  filesystem?: SandboxGameplayFeaturePatchFilesystem,
): GovernedRuntimeAdapter {
  const fs = resolveAdapterFilesystem(filesystem);

  return {
    adapterId: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID,
    runtimeType: "openclaw",
    adapterVersion: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_VERSION,
    capability: SANDBOX_GAMEPLAY_FEATURE_PATCH_CAPABILITY,
    defaultTimeoutMs: DEFAULT_TIMEOUT_MS,
    maxStdoutBytes: MAX_STDOUT_BYTES,
    maxStderrBytes: MAX_STDERR_BYTES,

    async invoke(invocation: GovernedRuntimeInvocation): Promise<RuntimeInvocationResult> {
      const startedAt = invocation.requestedAt;
      const invocationId = invocation.invocationId;
      let lifecycle = createRuntimeExecutionLifecycle(invocationId, startedAt);

      if (!invocation.ioContract.workspaceWriteAllowed) {
        const failedAt = new Date().toISOString();
        lifecycle = advanceLifecycleState(lifecycle, "rejected", failedAt,
          "IO contract forbids workspace write");
        return makeFailedInvocationResult({
          invocationId,
          dispatchId: invocation.dispatchId,
          sandboxId: invocation.sandboxId,
          runtimeType: "openclaw",
          adapterId: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID,
          failure: makeRuntimeFailure(
            "operation_rejected_by_adapter",
            "IO contract does not permit workspace writes. Set workspaceWriteAllowed: true.",
            failedAt,
          ),
          lifecycle,
          now: failedAt,
        });
      }

      const t0 = new Date().toISOString();
      lifecycle = advanceLifecycleState(lifecycle, "authorization_verified", t0,
        "Pre-authorized by dispatch orchestrator");
      lifecycle = advanceLifecycleState(lifecycle, "dispatching", t0,
        `Resolving ${SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME} path within sandbox workspace...`);

      const targetAbsolutePath = path.join(invocation.workspaceRoot, SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME);
      if (!isWithinWorkspace(invocation.workspaceRoot, targetAbsolutePath)) {
        const failedAt = new Date().toISOString();
        lifecycle = advanceLifecycleState(lifecycle, "failed", failedAt, "Sandbox boundary violation");
        return makeFailedInvocationResult({
          invocationId,
          dispatchId: invocation.dispatchId,
          sandboxId: invocation.sandboxId,
          runtimeType: "openclaw",
          adapterId: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID,
          failure: makeRuntimeFailure(
            "sandbox_boundary_violation",
            `Feature patch file path escapes workspace root: ${targetAbsolutePath}`,
            failedAt,
          ),
          lifecycle,
          now: failedAt,
        });
      }

      const t1 = new Date().toISOString();
      lifecycle = advanceLifecycleState(lifecycle, "running", t1,
        `Generating ${SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME} with stamina clamp helper...`);

      try {
        await fs.createDirectory(invocation.workspaceRoot);

        const existingContent = await fs.readFile(targetAbsolutePath);
        const patchLabel = invocation.operationRequest.slice(0, MAX_PATCH_LABEL_LENGTH) || "stamina clamp feature";

        let patchVersion = 1;
        let beforeContent = "(file did not exist — creating feature patch file)";
        let isFirstRun = true;

        if (existingContent !== null) {
          const versionMatch = existingContent.match(/Patch Version: (\d+)/);
          if (versionMatch && versionMatch[1]) {
            patchVersion = Math.max(1, parseInt(versionMatch[1], 10) + 1);
          }
          beforeContent = existingContent;
          isFirstRun = false;
        }

        const afterContent = generateFileContent(patchVersion, patchLabel);
        await fs.writeFile(targetAbsolutePath, afterContent);

        const completedAt = new Date().toISOString();
        const mutationDescription = isFirstRun
          ? `Created ${SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME} with stamina clamp helper (v1)`
          : `Updated ${SANDBOX_GAMEPLAY_FEATURE_PATCH_FILE_NAME} with new patch version (v${patchVersion})`;

        lifecycle = advanceLifecycleState(lifecycle, "completed", completedAt, mutationDescription);

        const stdoutLines = [
          "=== FEATURE PATCH: STAMINA REGENERATION CLAMP ===",
          `Patch Version: ${patchVersion}`,
          `Mutation: Inject StaminaHelper.ClampStaminaRegeneration()`,
          `Operation: ${patchLabel}`,
          "",
          "AFTER (C# code):",
          afterContent,
          "",
          mutationDescription,
        ];
        const stdout = stdoutLines.join("\n").slice(0, MAX_STDOUT_BYTES);

        return {
          invocationId,
          dispatchId: invocation.dispatchId,
          sandboxId: invocation.sandboxId,
          runtimeType: "openclaw",
          adapterId: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID,
          outcome: "completed",
          lifecycle,
          outputCapture: makeOutputCapture({
            stdout,
            stderr: [],
            maxStdoutBytes: MAX_STDOUT_BYTES,
            maxStderrBytes: MAX_STDERR_BYTES,
            capturedAt: completedAt,
          }),
          startedAt,
          completedAt,
          durationMs: Math.max(0, new Date(completedAt).getTime() - new Date(startedAt).getTime()),
          safetyBoundary: makeRuntimeAdapterSafetyBoundary(),
        };
      } catch (error) {
        const failedAt = new Date().toISOString();
        const errMsg = error instanceof Error ? error.message : String(error);
        lifecycle = advanceLifecycleState(lifecycle, "failed", failedAt, errMsg);
        return makeFailedInvocationResult({
          invocationId,
          dispatchId: invocation.dispatchId,
          sandboxId: invocation.sandboxId,
          runtimeType: "openclaw",
          adapterId: SANDBOX_GAMEPLAY_FEATURE_PATCH_ADAPTER_ID,
          failure: makeRuntimeFailure("unknown_failure", errMsg, failedAt),
          lifecycle,
          now: failedAt,
        });
      }
    },
  };
}
